# Generated by Django 4.2.3 on 2023-07-16 21:58

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, null=True)),
                ("subtitle", models.CharField(max_length=100, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("image", models.FileField(upload_to="uploads/")),
                ("body", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "Blog",
            },
            managers=[
                ("blogs", django.db.models.manager.Manager()),
            ],
        ),
    ]
