# Generated by Django 4.2.3 on 2023-07-27 01:56

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, null=True)),
                ("subtitle", models.CharField(max_length=100, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("A", "Activity"),
                            ("E", "Exclaim"),
                            ("C", "Code"),
                            ("L", "Lightning"),
                            ("S", "Stars"),
                            ("Q", "Question"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("body", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "Blog",
            },
            managers=[
                ("blogs", django.db.models.manager.Manager()),
            ],
        ),
    ]
