# Generated by Django 4.2.3 on 2023-07-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="image",
        ),
        migrations.AddField(
            model_name="blog",
            name="mood",
            field=models.CharField(
                choices=[
                    ("A", "Activity"),
                    ("E", "Exclaim"),
                    ("C", "Code"),
                    ("L", "Lightning"),
                    ("S", "Stars"),
                    ("Q", "Question"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
